index:
    path: /
    defaults: { _controller: 'App\Controller\HomePageController::index' }

user-index:
    path: /espace-utilisateur
    defaults: { _controller: 'App\Controller\UserController::index' }

admin-index:
    path: /admin
    defaults: { _controller: 'App\Controller\AdminController::index' }

login:
    path: /espace-utilisateur/login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
